spring:
  application:
    name: gerenciador_loja_backend

  profiles:
    active: prod # troque para prod em produção

  jackson:
    serialization:
      write-dates-as-timestamps: false
    date-format: yyyy-MM-dd'T'HH:mm:ss

api:
  security:
    token:
      secret: my-secret-key-2007

