##spring.application.name=gerenciador_loja_backend
##
#spring.datasource.url=${DATASOURCE_URL}
#spring.datasource.username=${DATASOURCE_USERNAME}
#spring.datasource.password=${DATASOURCE_PASSWORD}
#
#
##spring.jpa.show-sql=true
##spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
##
##spring.jackson.serialization.write-dates-as-timestamps=false
##spring.jackson.date-format=yyyy-MM-dd'T'HH:mm:ss
#
#
#spring.application.name=gerenciador_loja_backend
#
##spring.datasource.url=jdbc:postgresql://ep-crimson-credit-acoij617-pooler.sa-east-1.aws.neon.tech:5432/neondb?sslmode=require&channel_binding=require
##spring.datasource.username=neondb_owner
##spring.datasource.password=npg_OxRi1lNPqn5m
#
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
#spring.jpa.properties.hibernate.default_schema=public
#
#api.security.token.secret=${JWT_SECRET}
#
